# Generated by Django 5.2.5 on 2025-11-29 00:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
