# Generated by Django 5.2.5 on 2026-03-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0002_alter_content_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="duration",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="content",
            name="level",
            field=models.CharField(
                choices=[
                    ("Iniciante", "Iniciante"),
                    ("Intermediário", "Intermediário"),
                    ("Avançado", "Avançado"),
                ],
                default="Iniciante",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="tags",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="content",
            name="text_content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="content",
            name="thumbnail",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="content",
            name="video_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
