# Generated by Django 5.2.5 on 2026-03-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0003_content_duration_content_level_content_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="type",
            field=models.CharField(default="text", max_length=20),
        ),
    ]
